config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
    resources :jobs do
        get 'list', on: :collection
    end

   root 'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google]

  has_many :jobs

  def self.find_for_google_oauth2(auth, signed_in_resource=nil)
      user = User.where(:provider => auth.provider, :uid => auth.uid).first
      return user if user
      user = User.create(
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_job, only: [:show, :edit, :update, :destroy]


  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
    @jobs_by_date = @jobs.group_by(&:applied_date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  def list
    @jobs = Job.all
  end


  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @jobs = Job.all
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @jobs_by_date = @jobs.group_by(&:applied_date)
    respond_to do |format|
      if @job.save
        current_user.jobs << @job
        format.html { redirect_to jobs_url, notice: 'Job was successfully created.' }
        format.js {render :layout => false}
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.js {render :layout => false}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    def user_id
    @user = User.find(job.user_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:company_name, :job_title, :applied_date, :follow_up_date, :contact_name, :contact_phone, :notes, :additional_contacts, :user_id, :job_id)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

def google
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"

        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/jobs/_calendar.html.erb
<div class="container">
<div id="jobs">
  <h2 id="month">
    <%= link_to "<", date: @date.prev_month %>
    <%= @date.strftime("%B %Y") %>
    <%= link_to ">", date: @date.next_month %>
  </h2>

  <%= calendar @date do |date| %>
    <%= date.day %>
    <% if @jobs_by_date[date] %>
      <ul>
        <% @jobs_by_date[date].each do |job| %>
          <li><%= link_to job.company_name, job, id: "my_pony", class: "fancy-calendar" %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>
</div>

app/views/jobs/_form.html.erb
<%= bootstrap_form_for(@job, layout: :inline) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <%= f.text_field :company_name, id: "company_id", hide_label: :true, placeholder: "Company Name" %>

    <%= f.text_field :job_title, hide_label: :true, placeholder: "Job Title" %>

    <%= f.text_field :applied_date, hide_label: :true, id: "show_up", placeholder: "Applied Date" %>

    <%= f.text_field :contact_phone, hide_label: :true, prepend:"+1", :class => "form-control bfh-phone", placeholder: "Contact Phone" %>
</div>

<div class="container">
  <%= f.text_area :notes, hide_label: :true, placeholder: "Notes", :size => "67x10" %>

  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-warning', id: "submit" %>
  </div>


<% end %>

app/views/jobs/_list.html.erb
<table id="job_posted">
    <thead>
      <tr>
        <th>Company</th>
        <th>Title</th>
        <th>Date-applied</th>
        <!-- <th>Follow-up-date</th> -->
        <!-- <th>Contact</th> -->
        <!-- <th>Contact-phone</th> -->
        <th>Notes</th>
        <!-- <th>User Id</th> -->
        <!-- <th>Additional Contacts</th> -->
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @jobs.each do |job| %>
        <% if current_user.id == job.user_id %>
         <tr>
          <td><%= job.company_name %></td>
           <td><%= job.job_title %></td>
           <td><%#= job.applied_date %></td>
           <td><%#= job.follow_up_date %></td>
           <td><%#= job.contact_name %></td>
           <td><%#= job.contact_phone %></td>
           <td><%= job.notes %></td>
           <td><%#= job.additional_contacts %></td>
           <td><%= link_to 'Show', job %></td>
           <td><%= link_to 'Edit', job %></td>
           <td><%= link_to 'Delete', job, method: :delete,   data: {confirm: "Are you sure?"}, remote: true, class: "delete_pony" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
</table>

app/views/jobs/create.js.erb
// $('#new_job').remove();
// $('#new_link').show();
// $('#job_posted').html("<%= j render('list') %>");
// $('.calendar').html("<%= j render(:partial => 'jobs/calendar') %>");


// $('#submit').click(function() {
// $('div.fancybox-overlay.fancybox-overlay-fixed').hide();
// });

app/views/jobs/destroy.js.erb
$('.delete_pony').bind('ajax:success', function() {
    $(this).closest('tr').fadeOut();
    $('.calendar [href$="<%= @job.id %>"]').fadeOut();
    // $('div.fancybox-overlay.fancybox-overlay-fixed').hide();
});

app/views/jobs/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<% if current_user %>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">

      <a class="navbar-brand" href="/jobs"><%= "#{current_user.email} " %></a>
    </div>

    <p class="navbar-text"><%= link_to " #{current_user.jobs.count} ", list_jobs_path, id: "job_count", class: "fancybox" %>
    </p>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'New Job', new_job_path, class: "fancybox" %></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>




<div id="room_for_new_job">
</div>
<%= render 'calendar' %>


<% else %>

<!-- "Sign in with Google" -->
<section class="btn-login">
<%= link_to " Sign in with Google", user_omniauth_authorize_path(:google), class: "zocial googleplus"%>
</section>

<% end %>

app/views/jobs/list.html.erb
<table class="table table-hover", id="job_posted">
    <thead>
      <tr>
        <th>Company</th>
        <th>Title</th>
        <th>Date-applied</th>
        <!-- <th>Follow-up-date</th> -->
        <!-- <th>Contact</th> -->
        <!-- <th>Contact-phone</th> -->
        <th>Notes</th>
        <!-- <th>User Id</th> -->
        <!-- <th>Additional Contacts</th> -->
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @jobs.each do |job| %>
        <% if current_user.id == job.user_id %>
         <tr>
          <td><%= job.company_name %></td>
           <td><%= job.job_title %></td>
           <td><%#= job.applied_date %></td>
           <td><%#= job.follow_up_date %></td>
           <td><%#= job.contact_name %></td>
           <td><%#= job.contact_phone %></td>
           <td><%= job.notes %></td>
           <td><%#= job.additional_contacts %></td>
           <td><%= link_to 'Show', job %></td>
           <td><%= link_to 'Edit', job %></td>
           <td><%= link_to 'Delete', job, method: :delete,   data: {confirm: "Are you sure?"}, remote: true, class: "delete_pony" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
</table>

<%#= link_to "Home", jobs_path %>

app/views/jobs/new.html.erb
<br>

<br>

<%= render 'form' %>

</div>

app/views/jobs/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @job.company_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @job.job_title %>
</p>

<p>
  <strong>Date-applied:</strong>
  <%= @job.applied_date %>
</p>

<!-- <p>
  <strong>Follow-up-date:</strong>
  <%#= @job.follow_up_date %>
</p> -->

<!-- <p>
  <strong>Contact:</strong>
  <%#= @job.contact_name %>
</p> -->

<!-- <p>
  <strong>Contact-phone:</strong>
  <%#= @job.contact_phone %>
</p> -->

<p>
  <strong>Notes:</strong>
  <%= @job.notes %>
</p>

<!-- <p>
  <strong>Any additional contacts?</strong>
  <%#= @job.additional_contacts %>
</p> -->

<%= link_to 'Edit', edit_job_path(@job) %> |

<%= link_to 'Delete', @job, method: :delete,   data: {confirm: "Are you sure?"} %> |

<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trillapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <!-- <p class="notice"><%= notice %></p> -->

<% if current_user %>

  <%= yield %>

  <% else %>

  <div class="l-background-container">

  <header>
    <h1>TRILLAPP</h1>
    <h2>TRACK YOUR OPPORTUNITIES</h2>
  </header>

  <p class="alert"><%= alert %></p>
<!-- </div> container -->

<%= yield %>

</div> <!-- Background picture -->
</body>
</html>
<% end %>